Documentation-11-analyse-teacher-role
corentingoo/Learning_project_group_2 pull request #19
Opened 2022-10-25 15:50 UTC by corentingoo

2022-10-25 17:54 UTC, LydiaInes approved these changes

2022-10-27 18:44 UTC, EthanGoratel requested changes
format md

2022-10-27 19:26 UTC, francoisifo commented
Pour ton analyse technique, peut-être rajouter comment va se derouler le C - S - R pour ton Epic.  Afin qu'un developpeur qui va reprendre ton analyse sache comment cela va être réalisé techniquement, par quel controleur, web service  et le nom à donner au service... .

2022-10-29 12:51 UTC, francoisifo submitted a review, later dismissed
Pour ton analyse technique, peut-être rajouter comment va se derouler le C - S - R pour ton Epic. Afin qu'un developpeur qui va reprendre ton analyse sache comment cela va être réalisé techniquement, par quel controleur, web service et le nom à donner au service... .

2022-11-03 18:40 UTC, EthanGoratel reviewed
modifier la stories pour ajouter la connexion du student

2022-11-03 19:25 UTC, EthanGoratel approved these changes

2022-11-03 19:26 UTC, merged