documentation-17-analyse-de-la-recuperation-de-mot-de-passe
corentingoo/Learning_project_group_2 pull request #20
Opened 2022-10-25 17:22 UTC by LydiaInes

2022-10-25 17:27 UTC, corentingoo approved these changes

2022-10-25 17:35 UTC, corentingoo requested changes

2022-10-25 17:35 UTC, corentingoo commented on Docs/Epic PSW reset/analyse fonctionnelle.md
> +lien pour demander le reset du mot de passe
"ajouter un lien ..."

2022-10-25 17:35 UTC, corentingoo commented on Docs/Epic PSW reset/analyse technique.md
> +'reset_password_token' ajouté à la table - varchar(30)
quel table?

2022-10-25 17:35 UTC, corentingoo commented on Docs/Epic PSW reset/stories.md
> +L'utilisateur a oublié son mot de passe, il clique sur le bouton pour avoir un mail de réinialisation.
il faut plus "incarné" l'utilisateur

2022-10-27 17:55 UTC, corentingoo approved these changes

2022-10-27 18:40 UTC, EthanGoratel requested changes
utiliser les formats md

2022-10-27 18:42 UTC, EthanGoratel reviewed
format md

2022-10-27 19:28 UTC, francoisifo commented
Meme remarque que pour l Epic de corentin,   Pour ton analyse technique, peut-être rajouter comment va se derouler le C - S - R pour ton Epic.  
Afin qu'un developpeur qui va reprendre ton analyse sache comment cela va être réalisé techniquement, par quel controleur, web service  et le nom à donner au controler, service... .

2022-10-29 12:50 UTC, francoisifo requested changes, later dismissed
Meme remarque que pour l Epic de corentin, Pour ton analyse technique, peut-être rajouter comment va se derouler le C - S - R pour ton Epic.
Afin qu'un developpeur qui va reprendre ton analyse sache comment cela va être réalisé techniquement, par quel controleur, web service et le nom à donner au controler, service... .

2022-11-09 18:19 UTC, EthanGoratel approved these changes

2022-11-09 18:42 UTC, merged