documentation-14-analyse-creation-formation
corentingoo/Learning_project_group_2 pull request #21
Opened 2022-10-25 20:05 UTC by francoisifo

create formation analyse

2022-10-27 17:15 UTC, EthanGoratel requested changes
dans tes fichiers md, ajoute un espace après tes #, cela charge le format des titres(cfr fichier create user)

2022-10-27 17:37 UTC, corentingoo requested changes

2022-10-27 17:37 UTC, corentingoo commented on Docs/EPIC_create_formation/Analyse creation formation 14 _analyse tech.md
> +  [ 1 = préquis exigé]
pas besoin de pré-requis pour l'instant , on ne va pas encore géré ça

2022-10-27 17:37 UTC, corentingoo commented on Docs/EPIC_create_formation/Analyse creation formation 14 _analyse tech.md
> +- Nom du professeur (de type: char 180)
pas le nom, mais la fk du professeur

2022-10-27 17:37 UTC, corentingoo commented on Docs/EPIC_create_formation/Analyse creation formation 14 _analyse tech.md
> +  [ 1 = archivé]
là non-plus, pas encore besoin "d'archiver" la formation , on seras déterminer si elle est finie via les dates

2022-10-27 17:37 UTC, corentingoo commented on Docs/EPIC_create_formation/Analyse creation formation 14 _analyse tech.md
> +      [ 1 = autorisé]
comme dit precedement, on auras la fk récupérée et on pourras recupéré le professeur par là ( read pas encore créer)

2022-10-27 17:37 UTC, corentingoo commented on Docs/EPIC_create_formation/Analyse creation formation 14 _analyse tech.md
> +CSS Icon (FontAwesome Library - Sous license Open Font License OFL) => Source: https://fontawesome.com/
juste mettre ceux qu'on rajoute événtuellement , sinon ça créer du bruit

2022-10-27 17:37 UTC, corentingoo commented on Docs/EPIC_create_formation/Analyse creation formation 14 _analyse tech.md
> +
ça va un peu trop loin pour les exceptions , on ne pourras jamais catcher toutes les exceptions

2022-10-27 17:37 UTC, corentingoo commented on Docs/EPIC_create_formation/Analyse creation formation 14 _analyse tech.md
> +Solution: afficher un message d'erreur adéquat (voir erreur de 1 à 7) et corriger la donnée jusqu'a ce qu'elle soit Ok.
là c'est bon 👍

2022-10-27 17:37 UTC, corentingoo commented on Docs/EPIC_create_formation/Analyse creation formation 14 _modele de donnees.md
> +) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
à corriger avec les remarques d'en haut

2022-10-27 17:48 UTC, corentingoo reviewed
tu utilise une image avec un crud complet ,  ici , c'est juste la création (et recuperation)

2022-10-27 17:48 UTC, corentingoo commented on Docs/EPIC_create_formation/Analyse creation formation 14 _modele de donnees.md
> +(NULL, 'Stage de 3e', 'Ce stage de 240 périodes vous replonge dans l univers du travail en IT.', 'Mr Martin', '0','30','20230101','20230130','0');
nickel , quelques exemples en plus 👍

2022-10-27 17:48 UTC, corentingoo commented on Docs/EPIC_create_formation/Analyse creation formation 14 _stories.md
> +##Stories
les stories c'est ce "mettre dans la peau" d'un utilisateur et raconter son action en première personne

2022-10-27 18:53 UTC, francoisifo commented on Docs/EPIC_create_formation/Analyse creation formation 14 _analyse tech.md
> +CSS Icon (FontAwesome Library - Sous license Open Font License OFL) => Source: https://fontawesome.com/
Justement, on utilise tous ceux là.

2022-10-27 18:55 UTC, francoisifo commented on Docs/EPIC_create_formation/Analyse creation formation 14 _analyse tech.md
> +
Je n'ai pas mis toutes les exceptions. il y en a bien plus côté client et côté server.  J'ai gardé les exceptions  importantes.
Source officiel IANA => https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml#http-status-codes-1

2022-11-01 15:13 UTC, corentingoo reviewed
ajoute

2022-11-01 15:13 UTC, corentingoo commented on Docs/EPIC_create_formation/Analyse creation formation 14 _analyse tech.md
> +  [ 1 = archivé]
correction , ajouter des détail

2022-11-03 19:48 UTC, corentingoo requested changes

2022-11-03 19:48 UTC, corentingoo commented on README.md
> +Plateforme de gestion de formations.
pas faire ça ici , au pire dans une issue on rajoute de la doc dans le readme, ici on auras déjà les épics

2022-11-03 19:48 UTC, corentingoo commented on Docs/EPIC_create_formation/Analyse creation formation 14 _analyse fonct _V2.md
> +- Une formation ne peut pas être crée en même temps par deux personnes différentes. (Par exemple: deux admins ne peuvent pas créer une même formation en même temps.)
on ne gere pas encore ça

2022-11-03 19:48 UTC, corentingoo commented on Docs/EPIC_create_formation/Analyse creation formation 14 _analyse tech V2.md
> +      [ 1 = autorisé]
on ne gere pas encore ça

2022-11-03 19:48 UTC, corentingoo commented on Docs/EPIC_create_formation/Analyse creation formation 14 _modele de donnees V2.md
> +   fk_nom_prof VARCHAR(180) NOT NULL,
fk_prof

2022-11-03 19:48 UTC, corentingoo commented on Docs/EPIC_create_formation/Analyse creation formation 14 _stories V2.md
> +Sécurité: Deux admins ne peuvent pas créer une même formation en même temps dans la base de données.
c'est plus de l'analyse fonctionnelle qu'autre chose

2022-11-03 19:57 UTC, corentingoo commented on Docs/EPIC_create_formation/Analyse creation formation 14 _stories V2.md
> +Sécurité: Deux admins ne peuvent pas créer une même formation en même temps dans la base de données.
abandon

2022-11-11 08:44 UTC, merged