documentation-13-creation user
corentingoo/Learning_project_group_2 pull request #22
Opened 2022-10-27 17:04 UTC by EthanGoratel

documentation creation user

2022-10-27 18:04 UTC, corentingoo approved these changes

2022-10-27 18:24 UTC, LydiaInes submitted a review, later dismissed
Vérifier l'analyse de la première connexion

2022-10-27 19:32 UTC, francoisifo commented
Meme remarque que pour l Epic de corentin et Lydia,   Pour ton analyse technique, peut-être rajouter comment va se derouler le C - S - R pour ton Epic.  
Afin qu'un developpeur qui va reprendre ton analyse sache comment cela va être réalisé techniquement, par quel controleur, web service  et le nom à donner au controler, service... .

+ MockUp

2022-10-29 12:49 UTC, francoisifo requested changes, later dismissed
Meme remarque que pour l Epic de corentin et Lydia, Pour ton analyse technique, peut-être rajouter comment va se derouler le C - S - R pour ton Epic.
Afin qu'un developpeur qui va reprendre ton analyse sache comment cela va être réalisé techniquement, par quel controleur, web service et le nom à donner au controler, service... .

Ajouter le MockUp.

2022-11-03 19:23 UTC, merged