Feature 15 create user
corentingoo/Learning_project_group_2 pull request #43
Opened 2022-11-14 00:14 UTC by francoisifo

2022-11-14 18:15 UTC, EthanGoratel requested changes
Hello, pourrais tu repull la dev?

2022-11-14 18:20 UTC, corentingoo commented on pom.xml
> -    <description>Demo project for Spring Boot</description>
pour la n eme fois , focus sur juste la feature, ceci ne doit pas être fait ici (bon, c'est pas si grave ça peux rester , mais modifie juste les fichiers sur les quels tu est sensé travailler

2022-11-14 18:33 UTC, corentingoo requested changes

2022-11-14 18:33 UTC, corentingoo commented on src/main/java/be/ifosup/learning/LearningApplication.java
> +//@ComponentScan(basePackages ={"users.create"} )
à retirer si pas utilisé

2022-11-14 18:33 UTC, corentingoo commented on src/main/java/be/ifosup/learning/config/WebSecurityConfig.java
> +//    }
idem ici , si c'est pas utilisé , retire

2022-11-14 18:33 UTC, corentingoo commented on src/main/resources/db/migration/V1_0_0__init.sql
alors , non , il faut créer un sql qui modifie les tables , le V1_0_0 , ne changeras jamais

2022-11-14 18:33 UTC, corentingoo commented on src/main/resources/db/migration/V1_2_0__modif_users.sql
> +ALTER TABLE users ADD email VARCHAR(50) NOT NULL AFTER username;
parfais, dans ce genre qu'il faut changer la db

2022-11-14 18:33 UTC, corentingoo commented on src/main/resources/templates/admin/index.html
> +    <!-- <input class="createbtn" name="ajouterUtilisateur" type="button" value="Ajouter un utilisateur" onclick="" /> -->
supprime les commentaires non-utiles

2022-11-14 18:33 UTC, corentingoo commented on src/main/resources/templates/admin/users/index.html
> +    <!-- <input class="createbtn" name="ajouterUtilisateur" type="button" value="Ajouter un utilisateur" onclick="" /> -->
pareil ici, supprime les commentaires non-utiles

2022-11-15 09:10 UTC, francoisifo commented on pom.xml
> -    <description>Demo project for Spring Boot</description>
Bien sûr, on le modifie selon le titre de notre projet.

2022-11-15 09:11 UTC, francoisifo commented on src/main/java/be/ifosup/learning/LearningApplication.java
> +//@ComponentScan(basePackages ={"users.create"} )
Utile pour le review/test.

2022-11-15 09:11 UTC, francoisifo commented on src/main/java/be/ifosup/learning/config/WebSecurityConfig.java
> +//    }
Utile pour le review/test.

2022-11-15 09:13 UTC, francoisifo commented on src/main/resources/db/migration/V1_0_0__init.sql
Alors non, autant que cela soit conforme au standard utf8 dès le départ.

2022-11-15 09:14 UTC, francoisifo commented on src/main/resources/templates/admin/index.html
> +    <!-- <input class="createbtn" name="ajouterUtilisateur" type="button" value="Ajouter un utilisateur" onclick="" /> -->
C'est utile pour la review et les tests.

2022-11-15 09:14 UTC, francoisifo commented on src/main/resources/templates/admin/users/index.html
> +    <!-- <input class="createbtn" name="ajouterUtilisateur" type="button" value="Ajouter un utilisateur" onclick="" /> -->
Pareil, c est utile.

2022-11-16 18:40 UTC, corentingoo commented on src/main/resources/db/migration/V1_0_0__init.sql
sauf que nous on as déjà le départ

2022-11-19 17:25 UTC, francoisifo commented
Need help for debug.

2022-12-08 21:17 UTC, corentingoo commented
branche très en retard comparé à la dev et feature faite pars lydia au final

2022-12-08 21:17 UTC, closed without merging